#!/bin/sh

# Inspired by https://github.com/ray-pH/polybar-cava

pkill -f "cava -p $HOME/.config/xmobar/scripts/cava_config"

bar_pipe="/tmp/cavabar.fifo"
if [ -p "$bar_pipe" ]; then
    dd if="$bar_pipe" iflag=nonblock of=/dev/null
else
    mkfifo "$bar_pipe" || exit 1
fi

exec cava -p "$HOME/.config/xmobar/scripts/cava_config" \
    | "$HOME/.config/xmobar/scripts/cavamap" 10 \
    > "$bar_pipe"
